# Generated by Django 5.2 on 2025-05-06 03:22

import libros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=libros.models.libro_portada_path, verbose_name='Imagen de Portada'),
        ),
    ]
