# Generated by Django 5.2 on 2025-05-05 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retrasado', 'Retrasado'), ('devuelto', 'Devuelto'), ('perdido', 'Perdido')], default='activo', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.now)),
                ('estado_libro', models.CharField(choices=[('bueno', 'Bueno'), ('dañado', 'Dañado'), ('perdido', 'Perdido')], default='bueno', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
